databases:
  - name: expenseTracker
    databaseName: expensetracker_2emn
    user: expensetracker_2emn_user

services:
  - type: web
    name: ExpenseTracker
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expensetracker_2emn
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
